"""
Convert .docx to markdown.

Two sources of list markers are supported, both funneling into the same
"canonical pattern -> depth" mapping:

    1. Markers typed directly into the paragraph text (e.g. "C4.1.1.",
       "1.", "(a)", "Article III.", "1.1.1"). This is what many
       government / technical docs do — they don't use Word's numbering
       system, they just type the marker and tab over.

    2. Markers generated by Word's numbering system (<w:numPr>). The
       marker text is reconstructed from numbering.xml and counters.

For each detected marker, we build a canonical PATTERN by replacing
variable tokens with format placeholders:

    digits            ->  <N>
    single lowercase  ->  <a>
    single uppercase  ->  <A>
    lowercase roman   ->  <i>    (2+ chars, all valid Roman letters)
    uppercase roman   ->  <I>    (2+ chars, all valid Roman letters)
    word prefix       ->  kept literal (e.g. "Section ", "Chapter ")
    letter+digits     ->  <letter><N>   (e.g. "C4" -> "C<N>")
    separators        ->  kept literal (. - : ( ) [ ])

The order in which each unique pattern first appears IS the tier order.
First pattern seen = depth 1 (##). Second pattern = depth 2 (###). Etc.
"""

import re
from docx import Document
from docx.table import Table
from docx.text.paragraph import Paragraph
from docx.oxml.ns import qn


# ---------------------------------------------------------------------------
# Generic marker detection from paragraph text
# ---------------------------------------------------------------------------

# A marker is the first whitespace-delimited chunk at the start of the text,
# optionally preceded by a "word prefix" like "Section " or "Chapter ".
# We accept a wide variety of shapes here and then VALIDATE by requiring the
# canonical pattern to contain at least one structural token (<N>, <a>, etc.).

_MARKER_RE = re.compile(
    r'''^
    (?:
        ([A-Za-z]+)[ \t]+    # optional word prefix like "Section " (group 1)
    )?
    (
      [\(\[]?                                          # optional open bracket
      (?:[A-Za-z]*\d+|[A-Za-z]+)                        # first token
      (?:[.\-:](?:[A-Za-z]*\d+|[A-Za-z]+))*             # more tokens
      [\)\]]?                                          # optional close bracket
      [.:\)]?                                          # optional trailing punct
    )
    (?=[ \t]|$)
    ''',
    re.VERBOSE,
)

# Bullet characters that can start a list item (followed by whitespace).
_BULLET_CHARS = set('-*\u2022\u2023\u25E6\u2043\u2219')


def _classify_letters(letters):
    """Return the pattern token for a run of letters."""
    if len(letters) >= 2 and all(c in 'IVXLCDM' for c in letters):
        return '<I>'
    if len(letters) >= 2 and all(c in 'ivxlcdm' for c in letters):
        return '<i>'
    if len(letters) == 1:
        return '<a>' if letters.islower() else '<A>'
    # Word-like prefix: keep literal. Rare mid-marker, but possible.
    return letters


def _canonicalize(marker):
    """Turn a raw marker like 'C4.1.1.' into a pattern like 'C<N>.<N>.<N>'.
    Trailing . or : is stripped because authors are inconsistent about it
    (some write '1.' and '2.' while others mix '1' with '2.')."""
    out = []
    i = 0
    s = marker
    while i < len(s):
        c = s[i]
        if c.isdigit():
            j = i
            while j < len(s) and s[j].isdigit():
                j += 1
            out.append('<N>')
            i = j
        elif c.isalpha():
            j = i
            while j < len(s) and s[j].isalpha():
                j += 1
            out.append(_classify_letters(s[i:j]))
            i = j
        else:
            out.append(c)
            i += 1
    result = ''.join(out)
    # normalize away trailing . and : that vary by author (but leave )
    # and ] alone because those are structural)
    return result.rstrip('.:')


_STRUCT_TOKENS = ('<N>', '<a>', '<A>', '<i>', '<I>')


def _is_valid_pattern(pattern, raw_marker, remainder):
    """
    Reject things that look like a marker but aren't (abbreviations like
    'e.g.' or 'i.e.', references in prose like 'FAR 4.804-2.').
    """
    # must contain at least one structural (variable) token
    if not any(tok in pattern for tok in _STRUCT_TOKENS):
        return False
    # if the text after the marker starts with a comma, it's almost
    # certainly an inline abbreviation (e.g., i.e.,), not a list marker
    if remainder.lstrip().startswith(','):
        return False
    # overly long raw markers (>40 chars) are suspicious
    if len(raw_marker) > 40:
        return False
    return True


def _detect_text_marker(text):
    """
    Look at the start of `text` for a typed-in list marker.
    Returns (raw_marker, pattern, remainder_text) or None.
    """
    if not text:
        return None
    stripped = text.lstrip('\t ')
    if not stripped:
        return None

    # bullet style: "- text", "* text", "• text"
    if stripped[0] in _BULLET_CHARS and len(stripped) > 1 and stripped[1] in ' \t':
        return (stripped[0], 'bullet', stripped[2:].lstrip())

    m = _MARKER_RE.match(stripped)
    if not m:
        return None

    word_prefix = m.group(1) or ''
    body = m.group(2)
    raw_marker = (f'{word_prefix} {body}' if word_prefix else body)
    remainder = stripped[m.end():].lstrip()

    pattern_body = _canonicalize(body)
    pattern = (f'{word_prefix} {pattern_body}' if word_prefix else pattern_body)

    if not _is_valid_pattern(pattern, raw_marker, remainder):
        return None

    return raw_marker, pattern, remainder


# ---------------------------------------------------------------------------
# Word numbering system (for docs that do use it)
# ---------------------------------------------------------------------------

_FMT_TOKEN_FOR_NUMFMT = {
    'decimal':      '<N>',
    'decimalZero':  '<0N>',
    'lowerLetter':  '<a>',
    'upperLetter':  '<A>',
    'lowerRoman':   '<i>',
    'upperRoman':   '<I>',
    'ordinal':      '<Nth>',
}


def _numpr(pe):
    pPr = pe.find(qn('w:pPr'))
    if pPr is None:
        return None
    np = pPr.find(qn('w:numPr'))
    if np is None:
        return None
    nid_el = np.find(qn('w:numId'))
    if nid_el is None:
        return None
    nid = nid_el.get(qn('w:val'))
    if nid == '0':
        return None
    il_el = np.find(qn('w:ilvl'))
    il = int(il_el.get(qn('w:val'), '0')) if il_el is not None else 0
    return (nid, il)


def _load_numbering_defs(doc):
    defs = {}
    try:
        part = doc.part.numbering_part
    except Exception:
        return defs
    if part is None:
        return defs
    abs_defs = {}
    for a in part.element.findall(qn('w:abstractNum')):
        lvls = {}
        for l in a.findall(qn('w:lvl')):
            il = int(l.get(qn('w:ilvl'), '0'))
            f = l.find(qn('w:numFmt'))
            t = l.find(qn('w:lvlText'))
            s = l.find(qn('w:start'))
            lvls[il] = {
                'fmt': f.get(qn('w:val')) if f is not None else 'decimal',
                'text': t.get(qn('w:val')) if t is not None else f'%{il + 1}.',
                'start': int(s.get(qn('w:val'))) if s is not None else 1,
            }
        abs_defs[a.get(qn('w:abstractNumId'))] = lvls
    for n in part.element.findall(qn('w:num')):
        r = n.find(qn('w:abstractNumId'))
        if r is not None and r.get(qn('w:val')) in abs_defs:
            defs[n.get(qn('w:numId'))] = abs_defs[r.get(qn('w:val'))]
    return defs


def _numbering_pattern(nid, ilvl, defs):
    levels = defs.get(nid, {})
    lvl = levels.get(ilvl)
    if not lvl:
        return '<N>.'
    if lvl['fmt'] == 'bullet':
        return 'bullet'
    def sub(m):
        n = int(m.group(1))
        f = levels.get(n - 1, {}).get('fmt', 'decimal')
        return _FMT_TOKEN_FOR_NUMFMT.get(f, '<N>')
    return re.sub(r'%(\d+)', sub, lvl['text'])


def _to_roman(n):
    vals = [(1000,'M'),(900,'CM'),(500,'D'),(400,'CD'),(100,'C'),(90,'XC'),
            (50,'L'),(40,'XL'),(10,'X'),(9,'IX'),(5,'V'),(4,'IV'),(1,'I')]
    out = []
    for v, s in vals:
        while n >= v:
            out.append(s)
            n -= v
    return ''.join(out)


def _format_number(v, fmt):
    if fmt == 'decimal':
        return str(v)
    if fmt == 'decimalZero':
        return f'{v:02d}'
    if fmt == 'lowerLetter':
        return chr(ord('a') + v - 1) if v <= 26 else chr(ord('a') + (v - 1) % 26) * ((v - 1) // 26 + 1)
    if fmt == 'upperLetter':
        return chr(ord('A') + v - 1) if v <= 26 else chr(ord('A') + (v - 1) % 26) * ((v - 1) // 26 + 1)
    if fmt == 'lowerRoman':
        return _to_roman(v).lower()
    if fmt == 'upperRoman':
        return _to_roman(v)
    if fmt == 'ordinal':
        suf = 'th' if 10 <= v % 100 <= 20 else {1:'st', 2:'nd', 3:'rd'}.get(v % 10, 'th')
        return f'{v}{suf}'
    return str(v)


# ---------------------------------------------------------------------------
# Inline formatting and tables
# ---------------------------------------------------------------------------

def _format_runs(para):
    parts = []
    for r in para.runs:
        t = r.text
        if not t:
            continue
        if not t.strip():
            parts.append(t)
            continue
        lead = t[:len(t) - len(t.lstrip())]
        trail = t[len(t.rstrip()):]
        inner = t.strip()
        if r.bold and r.italic:
            parts.append(f'{lead}***{inner}***{trail}')
        elif r.bold:
            parts.append(f'{lead}**{inner}**{trail}')
        elif r.italic:
            parts.append(f'{lead}*{inner}*{trail}')
        else:
            parts.append(t)
    result = ''.join(parts) if parts else para.text
    result = re.sub(r'\*\*\*\*\*\*', '', result)
    result = re.sub(r'\*\*\*\*', '', result)
    return result


def _table_md(table):
    rows = [[c.text.strip().replace('\n', ' ') for c in r.cells] for r in table.rows]
    if not rows:
        return ''
    cols = max(len(r) for r in rows)
    pad = lambda r: (r + [''] * (cols - len(r)))[:cols]
    lines = [
        '| ' + ' | '.join(pad(rows[0])) + ' |',
        '| ' + ' | '.join('---' for _ in range(cols)) + ' |',
    ]
    lines += ['| ' + ' | '.join(pad(r)) + ' |' for r in rows[1:]]
    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# First pass: discover patterns in order of first appearance
# ---------------------------------------------------------------------------

def _discover_patterns(doc, defs):
    """
    Walk top-level paragraphs and collect unique patterns in order of first
    appearance. Checks Word numbering first (if present), else text marker.
    """
    seen = []
    counters = {}  # needed only to keep numbering-path state consistent
    for el in doc.element.body:
        if el.tag != qn('w:p'):
            continue
        info = _numpr(el)
        pattern = None
        if info:
            pattern = _numbering_pattern(info[0], info[1], defs)
        else:
            # text marker path
            para = Paragraph(el, doc)
            m = _detect_text_marker(para.text)
            if m:
                pattern = m[1]
        if pattern and pattern not in seen:
            seen.append(pattern)
    return seen


# ---------------------------------------------------------------------------
# Main walker
# ---------------------------------------------------------------------------

def _walk(doc):
    defs = _load_numbering_defs(doc)
    patterns = _discover_patterns(doc, defs)
    depth_map = {pat: i + 1 for i, pat in enumerate(patterns)}
    counters = {}

    def depth_for(pat):
        if pat not in depth_map:
            depth_map[pat] = len(depth_map) + 1
        return depth_map[pat]

    for el in doc.element.body:
        if el.tag == qn('w:tbl'):
            yield {'kind': 'table', 'text': _table_md(Table(el, doc))}
            continue
        if el.tag != qn('w:p'):
            continue

        para = Paragraph(el, doc)
        text = _format_runs(para)

        if not text.strip():
            yield {'kind': 'blank'}
            continue

        # heading styles
        style = (para.style.name or '').lower()
        hl = None
        for i in range(1, 7):
            if style.startswith(f'heading {i}'):
                hl = i
                break
        if style == 'title':
            hl = 1
        elif style == 'subtitle':
            hl = 2
        if hl:
            yield {'kind': 'heading', 'level': hl, 'text': text.strip()}
            continue

        # Word numbering first (if the paragraph has numPr)
        info = _numpr(el)
        if info:
            nid, il = info
            levels = defs.get(nid, {})
            lvl = levels.get(il)

            c = counters.setdefault(nid, {})
            for k in [k for k in c if k > il]:
                del c[k]
            start = lvl['start'] if lvl else 1
            c[il] = c[il] + 1 if il in c else start

            if lvl is None:
                parts = [str(c[k]) for k in sorted(c) if k <= il]
                marker = '.'.join(parts) + '.'
                fmt = 'decimal'
            elif lvl['fmt'] == 'bullet':
                marker, fmt = '', 'bullet'
            else:
                fmt = lvl['fmt']
                marker = lvl['text']
                for k in range(il + 1):
                    if k in levels:
                        v = c.get(k, levels[k]['start'])
                        marker = marker.replace(
                            f'%{k + 1}',
                            _format_number(v, levels[k]['fmt']),
                        )
                marker = re.sub(r'%\d+', '', marker)

            pattern = _numbering_pattern(nid, il, defs)
            d = depth_for(pattern)
            yield {
                'kind': 'list', 'source': 'numbering',
                'num_id': nid, 'ilvl': il,
                'depth': d, 'fmt': fmt, 'marker': marker,
                'pattern': pattern, 'text': text.strip(),
                'body': text.strip(),
            }
            continue

        # text-marker fallback
        m = _detect_text_marker(text)
        if m:
            raw_marker, pattern, remainder = m
            d = depth_for(pattern)
            fmt = 'bullet' if pattern == 'bullet' else 'text'
            yield {
                'kind': 'list', 'source': 'text',
                'num_id': None, 'ilvl': None,
                'depth': d, 'fmt': fmt, 'marker': raw_marker,
                'pattern': pattern, 'text': text.strip(),
                'body': remainder,
            }
            continue

        yield {'kind': 'body', 'text': text}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def convert(path):
    doc = Document(str(path))
    out = []

    def blank():
        if out and out[-1] != '':
            out.append('')

    for item in _walk(doc):
        k = item['kind']
        if k == 'blank':
            blank()
        elif k == 'table':
            blank()
            out.append(item['text'])
            out.append('')
        elif k == 'heading':
            blank()
            out.append('#' * item['level'] + ' ' + item['text'])
            out.append('')
        elif k == 'list':
            if item['fmt'] == 'bullet':
                out.append('    ' * (item['depth'] - 1) + '- ' + item['body'])
            else:
                prefix = '#' * min(item['depth'] + 1, 6)
                if item['source'] == 'numbering':
                    # marker is NOT in body text, so prepend it
                    line = f'{prefix} {item["marker"]} {item["body"]}' if item['marker'] else f'{prefix} {item["body"]}'
                else:
                    # text marker is ALREADY in the paragraph, so use it as-is
                    line = f'{prefix} {item["text"]}'
                blank()
                out.append(line)
                out.append('')
        elif k == 'body':
            out.append(item['text'])

    return re.sub(r'\n{3,}', '\n\n', '\n'.join(out)).strip()


def inspect(path):
    doc = Document(str(path))
    defs = _load_numbering_defs(doc)
    patterns = _discover_patterns(doc, defs)

    print('PATTERN TIERS  (order of first appearance -> depth)')
    print('-' * 70)
    for i, pat in enumerate(patterns):
        print(f'  depth {i + 1}  =  {pat!r}')
    print()

    hdr = f'{"kind":<6}  {"src":<4}  {"depth":<5}  {"pattern":<22}  {"marker":<14}  text'
    print(hdr)
    print('-' * len(hdr))
    count = 0
    for item in _walk(doc):
        k = item['kind']
        if k == 'blank':
            continue
        count += 1
        if count > 80:
            print('  ... (truncated)')
            break
        if k == 'list':
            src = item.get('source', '')[:4]
            pat = item['pattern'][:22]
            mk = str(item['marker'])[:14]
            txt = item['body'][:55]
            print(f'{"list":<6}  {src:<4}  {item["depth"]:<5}  {pat:<22}  {mk:<14}  {txt}')
        elif k == 'heading':
            print(f'{"H" + str(item["level"]):<6}  {"":<4}  {"":<5}  {"":<22}  {"":<14}  {item["text"][:55]}')
        elif k == 'body':
            print(f'{"body":<6}  {"":<4}  {"":<5}  {"":<22}  {"":<14}  {item["text"][:55]}')
        elif k == 'table':
            print(f'{"table":<6}')
    print()
